package by.compit.yauheni.zhukovich.nsi_product.repository.model.ctl;

import java.math.BigDecimal;
import java.time.LocalDate;
import javax.persistence.Cacheable;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.Id;
import javax.persistence.Table;

import org.hibernate.annotations.CacheConcurrencyStrategy;

@Entity
@Table(name = "CARD")
@Cacheable
@org.hibernate.annotations.Cache(usage = CacheConcurrencyStrategy.READ_WRITE)
public class Card {

    @Id
    @Column(name = "ID")
    private Long id;
    @Column(name = "SYS_ID")
    private Long sysId;
    @Column(name = "NAME")
    private String name;
    @Column(name = "VALIDITY_MONTHS")
    private String validityMonths;
    @Column(name = "BIN")
    private String bin;
    @Column(name = "CARD_TYPE")
    private Long cardType;
    @Column(name = "CARD_TYPE_LEVEL")
    private String cardTypeLevel;
    @Column(name = "CURRENCY")
    private Long currency;
    @Column(name = "MINIMUM_BALANCE_RESIDENT")
    private BigDecimal minimumBalanceResident;
    @Column(name = "MINIMUM_BALANCE_NONRESIDENT")
    private BigDecimal minimumBalanceNonresident;
    @Column(name = "PRESET_DENOMINATION")
    private BigDecimal presetDenomination;
    @Column(name = "CARD_TYPE2")
    private String cardType2;
    @Column(name = "NAME_LANGUAGE_ON_THE_CARD")
    private Integer nameLanguageOnTheCard;
    @Column(name = "NAME_ON_THE_CARD")
    private String nameOnTheCard;
    @Column(name = "URL")
    private String url;
    @Column(name = "ISIS")
    private Long isis;
    @Column(name = "ONLINE_ORDER")
    private Boolean onlineOrder;
    @Column(name = "SPEC_ORDER_PROC_FEES31W32W")
    private Boolean specOrderProcFees31w32w;
    @Column(name = "RELEASE_AS_MAIN")
    private Boolean releaseAsMain;
    @Column(name = "POSSIB_DEPOSIT_ISSUE_VIRT_TERM")
    private Boolean possibDepositIssueVirtTerm;
    @Column(name = "PROHIB_CARD_RENEWAL")
    private Boolean prohibCardRenewal;
    @Column(name = "PROHIB_CARD_REPLACEMENT")
    private Boolean prohibCardReplacement;
    @Column(name = "RELEASE_AS_ADDITIONAL")
    private Boolean releaseAsAdditional;
    @Column(name = "AVAILABLE_FOR_CASHBACK")
    private Boolean availableForCashback;
    @Column(name = "PIN_CVV_SMS_SENDING")
    private Boolean pinCvvSmsSending;
    @Column(name = "ANALYSIS_B_N_REVOLUTIONS")
    private Boolean analysisBNRevolutions;
    @Column(name = "PART_ACT_MEGATRANSFORMER")
    private Boolean partActMegatransformer;
    @Column(name = "FORBID_CASH_FROM_CARD_ACC")
    private Boolean forbidCashFromCardAcc;
    @Column(name = "NOTINCLUDE_CARD_ACCAGR_DAYLIST")
    private Boolean notincludeCardAccagrDaylist;
    @Column(name = "PROHIB_REPLAC_CARD_PUMP_CARD")
    private Boolean prohibReplacCardPumpCard;
    @Column(name = "MIIK")
    private Boolean miik;
    @Column(name = "INDIVIDUAL_DESIGN")
    private Boolean individualDesign;
    @Column(name = "CANCEL_CHECK_SUBCARD")
    private Boolean cancelCheckSubcard;
    @Column(name = "SAVE_CARD_NAME_REPLAC_AUXCARD")
    private Boolean saveCardNameReplacAuxcard;
    @Column(name = "NOINTERNET_OPT_AVAILABLE")
    private Boolean nointernetOptAvailable;
    @Column(name = "FREE_VIEW_BALANCE_CALLCONTCENT")
    private Boolean freeViewBalanceCallcontcent;
    @Column(name = "ALLOW_COMMISSION_ONLINE_ORDER")
    private Boolean allowCommissionOnlineOrder;
    @Column(name = "EMV_APPID")
    private Long emvAppid;
    @Column(name = "EMV_DESIGNID")
    private Long emvDesignid;
    @Column(name = "VIRTUAL_CARD")
    private Boolean virtualCard;
    @Column(name = "AUTOMATIC_EMISSION")
    private Boolean automaticEmission;
    @Column(name = "CARD_FOR_DBO")
    private Boolean cardForDBO;
    @Column(name = "MINIMUM_NUMBER_OF_CARDS")
    private Long minimumNumberOfCards;
    @Column(name = "NUMBER_CARDS_GENERATE")
    private Long numberCardsGenerate;
    @Column(name = "ALLOW_SETTING_LIMITS")
    private Boolean allowSettingLimits;
    @Column(name = "FOR_INSTALL_IN_BRIS")
    private BigDecimal forInstallInBris;
    @Column(name = "FOR_INSTALL_INTERNET_BANKING")
    private BigDecimal forInstallInternetBanking;
    @Column(name = "ABIL_EDIT_NAME_ON_MAP")
    private Boolean abilEditNameOnMap;
    @Column(name = "NAME_LENGTH_ON_MAP")
    private Long nameLengthOnMap;
    @Column(name = "RENEWAL_ALLOWED")
    private Boolean renewalAllowed;
    @Column(name = "REPLACEMENT_ALLOWED")
    private Boolean replacementAllowed;
    @Column(name = "MEDIA_VIEW")
    private String mediaView;
    @Column(name = "CARD_TYPE3")
    private String cardType3;
    @Column(name = "SOCIAL_AFFIL_PURPOSE")
    private Long socialAffilPurpose;
    @Column(name = "ADDITIONAL_SERVICES")
    private Long additionalServices;
    @Column(name = "COBRAND")
    private Boolean cobrand;
    @Column(name = "CONTACTLESS")
    private Boolean contactless;
    @Column(name = "AIR_MILES_FACT_TRAVEL_MILES")
    private Long airMilesFactTravelMiles;
    @Column(name = "BONUS_AMOUNT")
    private Long bonusAmount;
    @Column(name = "THRESH_AMNT_OPERAT_LIFE_BONUS")
    private BigDecimal threshAmntOperatLifeBonus;
    @Column(name = "REQUIRED")
    private Long required;
    @Column(name = "OPTIONAL_FREE")
    private Long optionalFree;
    @Column(name = "OPTIONAL_PAID")
    private Long optionalPaid;
    @Column(name = "AUTOMAT_INTEREST_RATE_CHANGE")
    private Boolean automatInterestRateChange;
    @Column(name = "BID_VALUE")
    private BigDecimal bidValue;
    @Column(name = "UVKV_LIST")
    private String uvkvList;
    @Column(name = "DEFAULT_UVKV")
    private Long defaultUvkv;
    @Column(name = "LIST_RISK_GROUPS")
    private Long listRiskGroups;
    @Column(name = "DEFAULT_RISK_GROUP")
    private String defaultRiskGroup;
    @Column(name = "TRANSF_RATE_RENEWING_CARD")
    private Boolean transfRateRenewingCard;
    @Column(name = "PROHIB__ADDITIONAL_CONTRBTNS")
    private Boolean prohibAdditionalContrbtns;
    @Column(name = "LIST_VALID_PRODUCTS")
    private String listValidProducts;
    @Column(name = "TRANSFER_RATE_RENEW_CARD")
    private Boolean transferRateRenewCard;
    @Column(name = "RESCHED_RATE_INCREAS_OVRDRFT")
    private Boolean reschedRateIncreasOvrdrft;
    @Column(name = "RESCHED_RATE_REPLAC_CARD")
    private Boolean reschedRateReplacCard;
    @Column(name = "LIST_VALID_PRODUCTS2")
    private String listValidProducts2;
    @Column(name = "ADDPACK_PACKAGE_LIST")
    private String addpackPackageList;
    @Column(name = "ADDPACK_NUM_CARDS_PACKAGES")
    private Long addpackNumCardsPackages;
    @Column(name = "ADDPACK_GROUP_NAME")
    private String addpackGroupName;
    @Column(name = "ADDPACK_PAID_PACKAGES")
    private Boolean addpackPaidPackages;
    @Column(name = "ADDPACK_PACKAGE_NAME")
    private String addpackPackageName;
    @Column(name = "VALPACK_PACKAGE_LIST")
    private String valpackPackageList;
    @Column(name = "VALPACK_NUM_CARDS_PACKAGES")
    private Long valpackNumCardsPackages;
    @Column(name = "VALPACK_GROUP_NAME")
    private String valpackGroupName;
    @Column(name = "VALPACK_PAID_PACKAGES")
    private Boolean valpackPaidPackages;
    @Column(name = "VALPACK_PACKAGE_NAME")
    private String valpackPackageName;
    @Column(name = "LIST_OF_FINES")
    private String listOfFines;
    @Column(name = "DATE_FINES")
    private LocalDate dateFines;
    @Column(name = "AMOUNT_FINES")
    private BigDecimal amountFines;
    @Column(name = "TERM_FINES")
    private Long termFines;
    @Column(name = "TYPE_TERM_FINES")
    private String typeTermFines;
    @Column(name = "CHANGE_UPON_RENEWAL")
    private String changeUponRenewal;
    @Column(name = "CHANGE_UPON_REPLACEMENT")
    private String changeUponReplacement;
    @Column(name = "MANUAL_TRANSLAT_CHANGE")
    private String manualTranslatChange;
    @Column(name = "MEGA_PACKAGE_LIST")
    private String megaPackageList;
    @Column(name = "MEGA_PACKAGE_TO_TRANSFER")
    private String megaPackageToTransfer;
    @Column(name = "MEGA_AMNT_CASHLESS_DEBIT")
    private BigDecimal megaAmntCashlessDebit;
    @Column(name = "MEGA_SHARE_NONCASHDEBT_PROC")
    private BigDecimal megaShareNoncashdebtProc;
    @Column(name = "MEGA_DISCOUNT_PROC")
    private Long megaDiscountProc;
    @Column(name = "MEGA_NOTE_IB")
    private String megaNoteIB;
    @Column(name = "MEGA_MESSAGE_IB")
    private String megaMessageIB;
    @Column(name = "REWARD_CODE")
    private String rewardCode;
    @Column(name = "NAME_REWARD")
    private String nameReward;
    @Column(name = "AMOUNT_REWARD")
    private BigDecimal amountReward;
    @Column(name = "REWARD_CURRENCY")
    private Long rewardCurrency;
    @Column(name = "PLACE_OF_OPERATION")
    private Long placeOfOperation;
    @Column(name = "BOARD_METHOD")
    private Long boardMethod;
    @Column(name = "TARIFF_VALID_PERIOD_FROM")
    private LocalDate tariffValidPeriodFrom;
    @Column(name = "TARIFF_VALID_PERIOD_FOR")
    private LocalDate tariffValidPeriodFor;
    @Column(name = "NOTE")
    private String note;
    @Column(name = "VALIDITY_PERIOD_WITH")
    private Long validityPeriodWith;
    @Column(name = "VALIDITY_PERIOD_FOR")
    private BigDecimal validityPeriodFor;
    @Column(name = "SALARY_BASIC")
    private String salaryBasic;
    @Column(name = "SALARY_ADDITIONAL")
    private Boolean salaryAdditional;
    @Column(name = "SALARY_AUXILIARY")
    private Boolean salaryAuxiliary;
    @Column(name = "PERSONAL_CORE")
    private Boolean personalCore;
    @Column(name = "PERSONAL_EXTRAS")
    private Boolean personalExtras;
    @Column(name = "PERSONAL_HELPER")
    private Boolean personalHelper;
    @Column(name = "CORPORATE")
    private Boolean corporate;
    @Column(name = "ABLTY_CHANGE_PARAM_DISCOUNT")
    private Boolean abltyChangeParamDiscount;
    @Column(name = "DISCOUNT_PROC")
    private BigDecimal discountProc;
    @Column(name = "ADDED_BY_USER")
    private Boolean addedByUser;
    @Column(name = "WHEN_CREAT_CARD_NEW_CARD")
    private Boolean whenCreatCardNewCard;
    @Column(name = "WHEN_RENEWING_CARD")
    private Boolean whenRenewingCard;
    @Column(name = "WHEN_REPLC_CARD_MAINT_VALID")
    private Boolean whenReplcCardMaintValid;
    @Column(name = "WHEN_REPLC_CARD_CHANG_VALID")
    private Boolean whenReplcCardChangValid;
    @Column(name = "WHEN_SEND_PINCW_CARD_VIA_SMS")
    private Boolean whenSendPincwCardViaSms;
    @Column(name = "MIN_AMNT_CASHLSS_TRNVR_BYN")
    private BigDecimal minAmntCashlssTrnvrByn;
    @Column(name = "CARD_SERVICE_CHRG_PROC_DSCNT")
    private BigDecimal cardServiceChrgProcDscnt;
    @Column(name = "IS_FREE")
    private Boolean isFree;
    @Column(name = "SMS_TARIFF_PLANS_ALRTS_NMS")
    private String smsTariffPlansAlrtsNms;
    @Column(name = "LIST_OF_ORGANIZATIONS")
    private String listOfOrganizations;
    @Column(name = "DELIVERY")
    private Boolean delivery;

}